export default {
  error_internal_error: "Internal error",
  error_user_not_created: "User not created",
  error_env: "Environment variable is missing :",
  error_not_found: "Endpoint not found",
  error_invalid_user: "Invalid username or password",
  error_user_already_exists: "User already exists",
  error_invalid_db_validation: "Provide correct data for update or add",
  error_email_failed: "Failed to sent email",
  error_resend_email: "Your OTP has expired or invalid otp",
  error_invalid_headers: "Forbidden",
  error_invalid_env: "Environment must be prod or dev",
  msg_email_sent_verbose: 'Email sent to %s with Subject: "%s"',
  msg_email_sent: "Email sent to the address you provided.",
  msg_registered: "You are now registered",
  msg_updated: "Updated",
  msg_email_reset_email:
    "Email sent to the address you provided if found in the database",
  msg_empty: "No data found",
  error_missing_value: "Missing value:",
  error_missing_header: "Missing Header Value:",
  error_invalid_header: "Invalid Header Value",
  error_invalid_select_req:
    "Quantity must be smaller than stock or Provider's label is set to false",
};
